INITIATOR='INITIATOR'
PASSIVE='PASSIVE'
SATELITE='SATELITE'
PARTNER='PARTNER'
ORIGINATOR='ORIGINATOR'

ROLE='ROLE'
STATE='STATE'
MSGS="MESSAGES"


ASK_SWAP='ASK_SWAP'
WAIT_ASK_RESPONSE='WAIT_ASK_RESPONSE'
SEND_ACCEPT_SWAP='SEND_ACCEPT_SWAP'
SEND_TABLE='SEND_TABLE'
WAIT_LOCKS_UTABLE='WAIT_LOCKS_UTABLE'
PERFORM_SWAP='PERFORM_SWAP'
UPDATE_SATELITES='UPDATE_SATELITES'

WAIT_INIT_TABLE='WAIT_INIT_TABLE'
WAIT_FINAL_TABLE='WAIT_FINAL_TABLE'

WAIT_UPDATE='WAIT_UPDATE'
