---
experiment:
    name: P2_zabbix_test
    description: P2PClouds overlay experiment 
    walltime: 3600000 #seconds

    monitoring:
        site: fr-inria
        img: BonFIRE Zabbix Aggregator v7 
        application:
           name: p2ner
           trappers:
               - key: p2ner.energy
                 description: 'peer energy'
                 type: 2
                 value_type: 0
                 percentile: True

               - key: p2ner.scheduler
                 description: 'peer scheduler'
                 type: 2
                 value_type: 0
                 percentile: True
                
               - key: p2ner.swapInitiators
                 description: 'number of initiating swap'
                 type: 2
                 value_type: 3
                 percentile: True
                 
               - key: p2ner.swapSatelites
                 description: 'number of being a satelite'
                 type: 2
                 value_type: 3
                 percentile: True
                   
               - key: p2ner.neighbors
                 description: 'number of neighbors'
                 type: 2
                 value_type: 3
                 percentile: True
                
               - key: p2ner.log
                 description: 'log messages'
                 type: 2
                 value_type: 4
                 percentile: False

    vizir:
        site: fr-inria
        img: p2pcloudsV5
        
    subnets:
        - name: source
          address: 192.168.1.1
          size: C
          lossrate: 0
          bandwidth: 1000
          latency: 5
          
        - name: local1
          address: 192.168.2.1
          size: C
          lossrate: 0.0
          bandwidth: 20
          latency: 100
          
        - name: local2
          address: 192.168.3.1
          size: C
          lossrate: 0.0
          bandwidth: 10
          latency: 150
          
    router:
        - site: be-ibbt
          img: BonFIRE Debian Squeeze 2G v4
          net: 
             - BonFIRE WAN
             - producer
             - local1
             - local2

    clients:

        - name: producer
          site: be-ibbt
          img: BonFIRE Debian Squeeze 2G v4
          net: 
             - source
             - BonFIRE WAN
          
        - name: client1
          site: be-ibbt
          img: BonFIRE Debian Squeeze 2G v4
          net: 
             - local1
             - BonFIRE WAN
          
        - name: client2
          site: be-ibbt
          img: BonFIRE Debian Squeeze 2G v4
          net: 
             - local2
             - BonFIRE WAN

